name: ml_general  # Name your environment
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pytorch
  # - pytorch-cuda=12.4
  - nose
  - numpy
  - pandas
  - seaborn
  - tabulate
  - matplotlib
  - scikit-learn
  
  - pip  # Ensure pip is available for installing pip packages
  - pip:
  - xgboost
  - imbalanced-learn
  - optuna
  - mysql-connector-python 
  - mysql
  - python-dotenv
  - flake8
  - pytest
  - pytest-cov

    # - scikit-learn 
    # - bayesian-optimization